"""GreyMatter MCP tools for domain: Access Groups.

GENERATED by scripts/generate_from_collection.py — do not edit by hand.
Regenerate via: python scripts/generate_from_collection.py
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

_DOC: dict[str, str] = {
    "accessGroup": "query accessGroup ($after: String, $filter: PodFilter, $first: Int, $order: PodOrder, $after1: String, $filter1: RoleFilter, $first1: Int, $order1: RoleOrder, $after2: String, $filter2: UserFilter, $first2: Int, $order2: UserOrder, $id: ID!) {\n    accessGroup (id: $id) {\n        createdAt\n        description\n        id\n        isDefault\n        name\n        pods (after: $after, filter: $filter, first: $first, order: $order) {\n            edges {\n                cursor\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n        roles (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n            edges {\n                cursor\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n        ssoGroups\n        updatedAt\n        users (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n            edges {\n                cursor\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n    }\n}",
    "accessGroups": "query accessGroups ($after: String, $filter: AccessGroupFilter, $first: Int, $notFilter: AccessGroupFilter, $order: AccessGroupOrder) {\n    accessGroups (after: $after, filter: $filter, first: $first, notFilter: $notFilter, order: $order) {\n        edges {\n            cursor\n            node {\n                createdAt\n                description\n                id\n                isDefault\n                name\n                ssoGroups\n                updatedAt\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
    "permissions": "query permissions {\n    permissions {\n        description\n        displayName\n        groups\n        name\n    }\n}",
    "pod": "query pod ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: CustomerFilter, $first1: Int, $notFilter: CustomerFilter, $order1: CustomerOrder, $after2: String, $filter2: UserFilter, $first2: Int, $order2: UserOrder, $id: ID!) {\n    pod (id: $id) {\n        accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n            edges {\n                cursor\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n        createdAt\n        customers (after: $after1, filter: $filter1, first: $first1, notFilter: $notFilter, order: $order1) {\n            edges {\n                cursor\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n        description\n        id\n        name\n        updatedAt\n        users (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n            edges {\n                cursor\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n    }\n}",
    "pods": "query pods ($after: String, $filter: PodFilter, $first: Int, $notFilter: PodFilter, $order: PodOrder) {\n    pods (after: $after, filter: $filter, first: $first, notFilter: $notFilter, order: $order) {\n        edges {\n            cursor\n            node {\n                createdAt\n                description\n                id\n                name\n                updatedAt\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
    "role": "query role ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: UserFilter, $first1: Int, $order1: UserOrder, $id: ID!) {\n    role (id: $id) {\n        accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n            edges {\n                cursor\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n        createdAt\n        description\n        id\n        name\n        permissions\n        type\n        updatedAt\n        users (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n            edges {\n                cursor\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n    }\n}",
    "roles": "query roles ($after: String, $filter: RoleFilter, $first: Int, $notFilter: RoleFilter, $order: RoleOrder) {\n    roles (after: $after, filter: $filter, first: $first, notFilter: $notFilter, order: $order) {\n        edges {\n            cursor\n            node {\n                createdAt\n                description\n                id\n                name\n                permissions\n                type\n                updatedAt\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
    "createAccessGroup": "mutation createAccessGroup ($after: String, $filter: PodFilter, $first: Int, $order: PodOrder, $after1: String, $filter1: RoleFilter, $first1: Int, $order1: RoleOrder, $after2: String, $filter2: UserFilter, $first2: Int, $order2: UserOrder, $input: CreateAccessGroupInput!) {\n    createAccessGroup (input: $input) {\n        accessGroup {\n            createdAt\n            description\n            id\n            isDefault\n            name\n            pods (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            roles (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n                totalCount\n            }\n            ssoGroups\n            updatedAt\n            users (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n                totalCount\n            }\n        }\n        success\n    }\n}",
    "createPod": "mutation createPod ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: CustomerFilter, $first1: Int, $notFilter: CustomerFilter, $order1: CustomerOrder, $after2: String, $filter2: UserFilter, $first2: Int, $order2: UserOrder, $input: CreatePodInput!) {\n    createPod (input: $input) {\n        pod {\n            accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            createdAt\n            customers (after: $after1, filter: $filter1, first: $first1, notFilter: $notFilter, order: $order1) {\n                totalCount\n            }\n            description\n            id\n            name\n            updatedAt\n            users (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n                totalCount\n            }\n        }\n        success\n    }\n}",
    "createRole": "mutation createRole ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: UserFilter, $first1: Int, $order1: UserOrder, $input: CreateRoleInput!) {\n    createRole (input: $input) {\n        role {\n            accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            createdAt\n            description\n            id\n            name\n            permissions\n            type\n            updatedAt\n            users (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n                totalCount\n            }\n        }\n        success\n    }\n}",
    "deleteAccessGroup": "mutation deleteAccessGroup ($id: ID!) {\n    deleteAccessGroup (id: $id) {\n        success\n    }\n}",
    "deletePod": "mutation deletePod ($id: ID!) {\n    deletePod (id: $id) {\n        success\n    }\n}",
    "deleteRole": "mutation deleteRole ($id: ID!) {\n    deleteRole (id: $id) {\n        success\n    }\n}",
    "updateAccessGroup": "mutation updateAccessGroup ($after: String, $filter: PodFilter, $first: Int, $order: PodOrder, $after1: String, $filter1: RoleFilter, $first1: Int, $order1: RoleOrder, $after2: String, $filter2: UserFilter, $first2: Int, $order2: UserOrder, $input: UpdateAccessGroupInput!) {\n    updateAccessGroup (input: $input) {\n        accessGroup {\n            createdAt\n            description\n            id\n            isDefault\n            name\n            pods (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            roles (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n                totalCount\n            }\n            ssoGroups\n            updatedAt\n            users (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n                totalCount\n            }\n        }\n        success\n    }\n}",
    "updatePod": "mutation updatePod ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: CustomerFilter, $first1: Int, $notFilter: CustomerFilter, $order1: CustomerOrder, $after2: String, $filter2: UserFilter, $first2: Int, $order2: UserOrder, $input: UpdatePodInput!) {\n    updatePod (input: $input) {\n        pod {\n            accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            createdAt\n            customers (after: $after1, filter: $filter1, first: $first1, notFilter: $notFilter, order: $order1) {\n                totalCount\n            }\n            description\n            id\n            name\n            updatedAt\n            users (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n                totalCount\n            }\n        }\n        success\n    }\n}",
    "updateRole": "mutation updateRole ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: UserFilter, $first1: Int, $order1: UserOrder, $input: UpdateRoleInput!) {\n    updateRole (input: $input) {\n        role {\n            accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            createdAt\n            description\n            id\n            name\n            permissions\n            type\n            updatedAt\n            users (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n                totalCount\n            }\n        }\n        success\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    @mcp.tool(name="access_group", description="Access Groups \u00b7 query accessGroup. Variables: after, filter, first, order, after1, filter1, first1, order1, after2, filter2, first2, order2, id. Example variables: {\"after\":\"T18w\",\"filter\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"id...")
    async def access_group(
        id: Annotated[str, Field(description="GraphQL: ID!")],
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
        after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter1: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
        first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order1: Annotated[Any | None, Field(default=None, description="GraphQL: RoleOrder")] = None,
        after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter2: Annotated[Any | None, Field(default=None, description="GraphQL: UserFilter")] = None,
        first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order2: Annotated[Any | None, Field(default=None, description="GraphQL: UserOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["accessGroup"], {"id": id, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

    @mcp.tool(name="access_groups", description="Access Groups \u00b7 query accessGroups. Variables: after, filter, first, notFilter, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"notFilter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"or...")
    async def access_groups(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        notFilter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["accessGroups"], {"after": after, "filter": filter, "first": first, "notFilter": notFilter, "order": order}, customer_slug=customer_slug)

    @mcp.tool(name="permissions", description="Access Groups \u00b7 query permissions. Example variables: {}")
    async def permissions(
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["permissions"], {}, customer_slug=customer_slug)

    @mcp.tool(name="pod", description="Access Groups \u00b7 query pod. Variables: after, filter, first, order, after1, filter1, first1, notFilter, order1, after2, filter2, first2, order2, id. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":...")
    async def pod(
        id: Annotated[str, Field(description="GraphQL: ID!")],
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
        after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter1: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerFilter")] = None,
        first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        notFilter: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerFilter")] = None,
        order1: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerOrder")] = None,
        after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter2: Annotated[Any | None, Field(default=None, description="GraphQL: UserFilter")] = None,
        first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order2: Annotated[Any | None, Field(default=None, description="GraphQL: UserOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["pod"], {"id": id, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "notFilter": notFilter, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

    @mcp.tool(name="pods", description="Access Groups \u00b7 query pods. Variables: after, filter, first, notFilter, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"notFilter\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"roles\":[\"<ID HERE>\"],\"users\":[\"...")
    async def pods(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        notFilter: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["pods"], {"after": after, "filter": filter, "first": first, "notFilter": notFilter, "order": order}, customer_slug=customer_slug)

    @mcp.tool(name="role", description="Access Groups \u00b7 query role. Variables: after, filter, first, order, after1, filter1, first1, order1, id. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID...")
    async def role(
        id: Annotated[str, Field(description="GraphQL: ID!")],
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
        after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter1: Annotated[Any | None, Field(default=None, description="GraphQL: UserFilter")] = None,
        first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order1: Annotated[Any | None, Field(default=None, description="GraphQL: UserOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["role"], {"id": id, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1}, customer_slug=customer_slug)

    @mcp.tool(name="roles", description="Access Groups \u00b7 query roles. Variables: after, filter, first, notFilter, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"notFilter\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"users\":[\"<I...")
    async def roles(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        notFilter: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: RoleOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["roles"], {"after": after, "filter": filter, "first": first, "notFilter": notFilter, "order": order}, customer_slug=customer_slug)

    if not read_only:
        @mcp.tool(name="create_access_group", description="Access Groups \u00b7 mutation createAccessGroup. Variables: after, filter, first, order, after1, filter1, first1, order1, after2, filter2, first2, order2, input. Example variables: {\"after\":\"T18w\",\"filter\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"id...")
        async def create_access_group(
            input: Annotated[Any, Field(description="GraphQL: CreateAccessGroupInput!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter1: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order1: Annotated[Any | None, Field(default=None, description="GraphQL: RoleOrder")] = None,
            after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter2: Annotated[Any | None, Field(default=None, description="GraphQL: UserFilter")] = None,
            first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order2: Annotated[Any | None, Field(default=None, description="GraphQL: UserOrder")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["createAccessGroup"], {"input": input, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

        @mcp.tool(name="create_pod", description="Access Groups \u00b7 mutation createPod. Variables: after, filter, first, order, after1, filter1, first1, notFilter, order1, after2, filter2, first2, order2, input. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":...")
        async def create_pod(
            input: Annotated[Any, Field(description="GraphQL: CreatePodInput!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter1: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerFilter")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            notFilter: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerFilter")] = None,
            order1: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerOrder")] = None,
            after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter2: Annotated[Any | None, Field(default=None, description="GraphQL: UserFilter")] = None,
            first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order2: Annotated[Any | None, Field(default=None, description="GraphQL: UserOrder")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["createPod"], {"input": input, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "notFilter": notFilter, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

        @mcp.tool(name="create_role", description="Access Groups \u00b7 mutation createRole. Variables: after, filter, first, order, after1, filter1, first1, order1, input. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID...")
        async def create_role(
            input: Annotated[Any, Field(description="GraphQL: CreateRoleInput!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter1: Annotated[Any | None, Field(default=None, description="GraphQL: UserFilter")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order1: Annotated[Any | None, Field(default=None, description="GraphQL: UserOrder")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["createRole"], {"input": input, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1}, customer_slug=customer_slug)

        @mcp.tool(name="delete_access_group", description="Access Groups \u00b7 mutation deleteAccessGroup. Variables: id. Example variables: {\"id\":\"<ID HERE>\"}")
        async def delete_access_group(
            id: Annotated[str, Field(description="GraphQL: ID!")],
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["deleteAccessGroup"], {"id": id}, customer_slug=customer_slug)

        @mcp.tool(name="delete_pod", description="Access Groups \u00b7 mutation deletePod. Variables: id. Example variables: {\"id\":\"<ID HERE>\"}")
        async def delete_pod(
            id: Annotated[str, Field(description="GraphQL: ID!")],
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["deletePod"], {"id": id}, customer_slug=customer_slug)

        @mcp.tool(name="delete_role", description="Access Groups \u00b7 mutation deleteRole. Variables: id. Example variables: {\"id\":\"<ID HERE>\"}")
        async def delete_role(
            id: Annotated[str, Field(description="GraphQL: ID!")],
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["deleteRole"], {"id": id}, customer_slug=customer_slug)

        @mcp.tool(name="update_access_group", description="Access Groups \u00b7 mutation updateAccessGroup. Variables: after, filter, first, order, after1, filter1, first1, order1, after2, filter2, first2, order2, input. Example variables: {\"after\":\"T18w\",\"filter\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"id...")
        async def update_access_group(
            input: Annotated[Any, Field(description="GraphQL: UpdateAccessGroupInput!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter1: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order1: Annotated[Any | None, Field(default=None, description="GraphQL: RoleOrder")] = None,
            after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter2: Annotated[Any | None, Field(default=None, description="GraphQL: UserFilter")] = None,
            first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order2: Annotated[Any | None, Field(default=None, description="GraphQL: UserOrder")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["updateAccessGroup"], {"input": input, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

        @mcp.tool(name="update_pod", description="Access Groups \u00b7 mutation updatePod. Variables: after, filter, first, order, after1, filter1, first1, notFilter, order1, after2, filter2, first2, order2, input. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":...")
        async def update_pod(
            input: Annotated[Any, Field(description="GraphQL: UpdatePodInput!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter1: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerFilter")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            notFilter: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerFilter")] = None,
            order1: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerOrder")] = None,
            after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter2: Annotated[Any | None, Field(default=None, description="GraphQL: UserFilter")] = None,
            first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order2: Annotated[Any | None, Field(default=None, description="GraphQL: UserOrder")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["updatePod"], {"input": input, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "notFilter": notFilter, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

        @mcp.tool(name="update_role", description="Access Groups \u00b7 mutation updateRole. Variables: after, filter, first, order, after1, filter1, first1, order1, input. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID...")
        async def update_role(
            input: Annotated[Any, Field(description="GraphQL: UpdateRoleInput!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter1: Annotated[Any | None, Field(default=None, description="GraphQL: UserFilter")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order1: Annotated[Any | None, Field(default=None, description="GraphQL: UserOrder")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["updateRole"], {"input": input, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1}, customer_slug=customer_slug)

