"""GreyMatter MCP tools for domain: API Keys.

GENERATED by scripts/generate_from_collection.py — do not edit by hand.
Regenerate via: python scripts/generate_from_collection.py
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

_DOC: dict[str, str] = {
    "apiKeys": "query apiKeys ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: PodFilter, $first1: Int, $order1: PodOrder, $after2: String, $filter2: RoleFilter, $first2: Int, $order2: RoleFilter, $user: ID) {\n    apiKeys (user: $user) {\n        createdAt\n        expiresAt\n        id\n        key\n        lastQuery\n        lastUsedAt\n        user {\n            accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            email\n            fullName\n            id\n            pods (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n                totalCount\n            }\n            roles (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n                totalCount\n            }\n            serviceNowId\n        }\n    }\n}",
    "createApiKey": "mutation createApiKey ($input: CreateApiKeyInput!) {\n    createApiKey (input: $input) {\n        apiKey {\n            createdAt\n            expiresAt\n            id\n            key\n            lastQuery\n            lastUsedAt\n            user {\n                email\n                fullName\n                id\n                serviceNowId\n            }\n        }\n        success\n    }\n}",
    "deleteApiKeyById": "mutation deleteApiKeyById ($id: ID!, $user: ID) {\n    deleteApiKeyById (id: $id, user: $user) {\n        success\n    }\n}",
    "deleteApiKeys": "mutation deleteApiKeys ($user: ID) {\n    deleteApiKeys (user: $user) {\n        success\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    @mcp.tool(name="api_keys", description="API Keys \u00b7 query apiKeys. Variables: after, filter, first, order, after1, filter1, first1, order1, after2, filter2, first2, order2, user. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID...")
    async def api_keys(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
        after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter1: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
        first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order1: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
        after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
        first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
        user: Annotated[str | None, Field(default=None, description="GraphQL: ID")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["apiKeys"], {"after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2, "user": user}, customer_slug=customer_slug)

    if not read_only:
        @mcp.tool(name="create_api_key", description="API Keys \u00b7 mutation createApiKey. Variables: input. Example variables: {\"input\":{\"expiryTime\":\"2026-05-01T00:00:00.000Z\",\"user\":\"<ID HERE>\"}}")
        async def create_api_key(
            input: Annotated[Any, Field(description="GraphQL: CreateApiKeyInput!")],
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["createApiKey"], {"input": input}, customer_slug=customer_slug)

        @mcp.tool(name="delete_api_key_by_id", description="API Keys \u00b7 mutation deleteApiKeyById. Variables: id, user. Example variables: {\"id\":\"<ID HERE>\",\"user\":\"<ID HERE>\"}")
        async def delete_api_key_by_id(
            id: Annotated[str, Field(description="GraphQL: ID!")],
            user: Annotated[str | None, Field(default=None, description="GraphQL: ID")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["deleteApiKeyById"], {"id": id, "user": user}, customer_slug=customer_slug)

        @mcp.tool(name="delete_api_keys", description="API Keys \u00b7 mutation deleteApiKeys. Variables: user. Example variables: {\"user\":\"<ID HERE>\"}")
        async def delete_api_keys(
            user: Annotated[str | None, Field(default=None, description="GraphQL: ID")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["deleteApiKeys"], {"user": user}, customer_slug=customer_slug)

