"""GreyMatter MCP tools for domain: Assets.

GENERATED by scripts/generate_from_collection.py — do not edit by hand.
Regenerate via: python scripts/generate_from_collection.py
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

_DOC: dict[str, str] = {
    "assets": "query assets ($after: String, $filter: AssetFilter, $first: Int, $order: AssetOrder) {\n    assets (after: $after, filter: $filter, first: $first, order: $order) {\n        edges {\n            cursor\n            node {\n                externalScanDetailsAvailable\n                id\n                ipAddress\n                name\n                operatingSystem\n                publiclyAccessible\n                techAssetIds\n                technology\n                type\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
    "deleteAsset": "mutation deleteAsset ($input: DeleteAssetInput!) {\n    deleteAsset (input: $input) {\n        message\n        success\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    @mcp.tool(name="assets", description="Assets \u00b7 query assets. Variables: after, filter, first, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"assetAccessibility\":\"ALL\",\"assetTypes\":[0],\"cloud\":{\"name\":\"\",\"visibility\":[\"LOGGING\"]},\"discoverTechnologies\":[\"\"],\"edr\":{\"name\":\"\",\"visibility\":[\"LOGGING\"]},\"eventFilter\":{\"activities\":[\"<ID HERE>\"],\"assetName\":\"<ID HERE>\",\"classes\":[\"<ID HERE>\"],\"eventCodes\":[\"\"],\"gr...")
    async def assets(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: AssetFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: AssetOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["assets"], {"after": after, "filter": filter, "first": first, "order": order}, customer_slug=customer_slug)

    if not read_only:
        @mcp.tool(name="delete_asset", description="Assets \u00b7 mutation deleteAsset. Variables: input. Example variables: {\"input\":{\"assetId\":\"<ID HERE>\",\"comment\":\"\"}}")
        async def delete_asset(
            input: Annotated[Any, Field(description="GraphQL: DeleteAssetInput!")],
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["deleteAsset"], {"input": input}, customer_slug=customer_slug)

