"""GreyMatter MCP tools for domain: Customer.

GENERATED by scripts/generate_from_collection.py — DO NOT EDIT BY HAND.
Any manual change here will be overwritten the next time the generator runs; to change a
tool, edit the generator (or the source Postman collection) and regenerate via:
    python scripts/generate_from_collection.py

How this module works:
  - `register(mcp, *, read_only)` is the entry point: the server calls it to register every
    tool in this domain onto the shared FastMCP instance.
  - `_DOC` maps each GraphQL operation name to its (possibly trimmed/pruned) GraphQL document
    string. Each tool below looks up its document in `_DOC` at call time.
  - Each generated tool is a thin async wrapper: it accepts typed parameters (one per GraphQL
    variable, plus an optional `customer_slug` header override) and forwards them as GraphQL
    variables to `execute_operation`, which performs the actual HTTP request.
  - Query tools are always registered. Mutation tools are registered ONLY when `read_only`
    is False, so a read-only deployment never exposes state-changing operations.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

# operation name -> GraphQL document string (after exclusions/trims/pruning were applied).
_DOC: dict[str, str] = {
    "customer": "query customer ($after: String, $first: Int, $after1: String, $first1: Int) {\n    customer {\n        accessControlPolicies (after: $after, first: $first) {\n            edges {\n                cursor\n                node {\n                    description\n                    displayName\n                    id\n                    name\n                    resource\n                    resourceType\n                }\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n        active\n        headerSlug\n        id\n        name\n        residency\n        slug\n        users (after: $after1, first: $first1) {\n            edges {\n                cursor\n                node {\n                    email\n                    fullName\n                    id\n                    serviceNowId\n                }\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n    }\n}",
    "customers": "query customers ($after: String, $filter: CustomerFilter, $first: Int, $notFilter: CustomerFilter, $order: CustomerOrder) {\n    customers (after: $after, filter: $filter, first: $first, notFilter: $notFilter, order: $order) {\n        edges {\n            cursor\n            node {\n                active\n                headerSlug\n                id\n                name\n                residency\n                slug\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    # --- Queries (always registered) ---
    # customer (query) — GraphQL operation, tool name "customer"
    @mcp.tool(name="customer", description="Customer \u00b7 query customer. Variables: after, first, after1, first1. Example variables: {\"after\":\"T18w\",\"first\":10,\"after1\":\"T18w\",\"first1\":10}")
    async def customer(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["customer"], {"after": after, "first": first, "after1": after1, "first1": first1}, customer_slug=customer_slug)

    # customers (query) — GraphQL operation, tool name "customers"
    @mcp.tool(name="customers", description="Customer \u00b7 query customers. Variables: after, filter, first, notFilter, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"accessGroups\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"notFilter\":{\"accessGroups\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"...")
    async def customers(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        notFilter: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerFilter")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["customers"], {"after": after, "filter": filter, "first": first, "notFilter": notFilter, "order": order}, customer_slug=customer_slug)

