"""GreyMatter MCP tools for domain: Customer.

GENERATED by scripts/generate_from_collection.py — do not edit by hand.
Regenerate via: python scripts/generate_from_collection.py
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

_DOC: dict[str, str] = {
    "customer": "query customer ($after: String, $first: Int, $after1: String, $first1: Int) {\n    customer {\n        accessControlPolicies (after: $after, first: $first) {\n            edges {\n                cursor\n                node {\n                    description\n                    displayName\n                    id\n                    name\n                    resource\n                    resourceType\n                }\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n        active\n        headerSlug\n        id\n        name\n        residency\n        slug\n        users (after: $after1, first: $first1) {\n            edges {\n                cursor\n                node {\n                    email\n                    fullName\n                    id\n                    serviceNowId\n                }\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n    }\n}",
    "customers": "query customers ($after: String, $filter: CustomerFilter, $first: Int, $notFilter: CustomerFilter, $order: CustomerOrder) {\n    customers (after: $after, filter: $filter, first: $first, notFilter: $notFilter, order: $order) {\n        edges {\n            cursor\n            node {\n                active\n                headerSlug\n                id\n                name\n                residency\n                slug\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    @mcp.tool(name="customer", description="Customer \u00b7 query customer. Variables: after, first, after1, first1. Example variables: {\"after\":\"T18w\",\"first\":10,\"after1\":\"T18w\",\"first1\":10}")
    async def customer(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["customer"], {"after": after, "first": first, "after1": after1, "first1": first1}, customer_slug=customer_slug)

    @mcp.tool(name="customers", description="Customer \u00b7 query customers. Variables: after, filter, first, notFilter, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"accessGroups\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"notFilter\":{\"accessGroups\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"...")
    async def customers(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        notFilter: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerFilter")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["customers"], {"after": after, "filter": filter, "first": first, "notFilter": notFilter, "order": order}, customer_slug=customer_slug)

