"""GreyMatter MCP tools for domain: Data.

GENERATED by scripts/generate_from_collection.py — do not edit by hand.
Regenerate via: python scripts/generate_from_collection.py
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

_DOC: dict[str, str] = {
    "dataSourceSchema": "query dataSourceSchema ($by: DataBy!) {\n    dataSourceSchema (by: $by) {\n        schema {\n            fields {\n                name\n                type\n            }\n        }\n    }\n}",
    "timeBuckets": "query timeBuckets ($filter: TimeBucketsFilter!) {\n    timeBuckets (filter: $filter) {\n        buckets {\n            count\n            endTime\n            startTime\n        }\n        unit\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    @mcp.tool(name="data_source_schema", description="Data \u00b7 query dataSourceSchema. Variables: by. Example variables: {\"by\":{\"incidentId\":\"<ID HERE>\"}}")
    async def data_source_schema(
        by: Annotated[Any, Field(description="GraphQL: DataBy!")],
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["dataSourceSchema"], {"by": by}, customer_slug=customer_slug)

    @mcp.tool(name="time_buckets", description="Data \u00b7 query timeBuckets. Variables: filter. Example variables: {\"filter\":{\"by\":{\"incidentId\":\"<ID HERE>\"},\"endTime\":\"2026-05-01T00:00:00.000Z\",\"query\":\"\",\"startTime\":\"2026-05-01T00:00:00.000Z\"}}")
    async def time_buckets(
        filter: Annotated[Any, Field(description="GraphQL: TimeBucketsFilter!")],
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["timeBuckets"], {"filter": filter}, customer_slug=customer_slug)

