"""GreyMatter MCP tools for domain: Data.

GENERATED by scripts/generate_from_collection.py — DO NOT EDIT BY HAND.
Any manual change here will be overwritten the next time the generator runs; to change a
tool, edit the generator (or the source Postman collection) and regenerate via:
    python scripts/generate_from_collection.py

How this module works:
  - `register(mcp, *, read_only)` is the entry point: the server calls it to register every
    tool in this domain onto the shared FastMCP instance.
  - `_DOC` maps each GraphQL operation name to its (possibly trimmed/pruned) GraphQL document
    string. Each tool below looks up its document in `_DOC` at call time.
  - Each generated tool is a thin async wrapper: it accepts typed parameters (one per GraphQL
    variable, plus an optional `customer_slug` header override) and forwards them as GraphQL
    variables to `execute_operation`, which performs the actual HTTP request.
  - Query tools are always registered. Mutation tools are registered ONLY when `read_only`
    is False, so a read-only deployment never exposes state-changing operations.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

# operation name -> GraphQL document string (after exclusions/trims/pruning were applied).
_DOC: dict[str, str] = {
    "dataSourceSchema": "query dataSourceSchema ($by: DataBy!) {\n    dataSourceSchema (by: $by) {\n        schema {\n            fields {\n                name\n                type\n            }\n        }\n    }\n}",
    "timeBuckets": "query timeBuckets ($filter: TimeBucketsFilter!) {\n    timeBuckets (filter: $filter) {\n        buckets {\n            count\n            endTime\n            startTime\n        }\n        unit\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    # --- Queries (always registered) ---
    # dataSourceSchema (query) — GraphQL operation, tool name "data_source_schema"
    @mcp.tool(name="data_source_schema", description="Data \u00b7 query dataSourceSchema. Variables: by. Example variables: {\"by\":{\"incidentId\":\"<ID HERE>\"}}")
    async def data_source_schema(
        by: Annotated[Any, Field(description="GraphQL: DataBy!")],
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["dataSourceSchema"], {"by": by}, customer_slug=customer_slug)

    # timeBuckets (query) — GraphQL operation, tool name "time_buckets"
    @mcp.tool(name="time_buckets", description="Data \u00b7 query timeBuckets. Variables: filter. Example variables: {\"filter\":{\"by\":{\"incidentId\":\"<ID HERE>\"},\"endTime\":\"2026-05-01T00:00:00.000Z\",\"query\":\"\",\"startTime\":\"2026-05-01T00:00:00.000Z\"}}")
    async def time_buckets(
        filter: Annotated[Any, Field(description="GraphQL: TimeBucketsFilter!")],
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["timeBuckets"], {"filter": filter}, customer_slug=customer_slug)

