"""GreyMatter MCP tools for domain: Detections.

GENERATED by scripts/generate_from_collection.py — do not edit by hand.
Regenerate via: python scripts/generate_from_collection.py
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

_DOC: dict[str, str] = {
    "customerDetection": "query customerDetection ($after: String, $filter: CustomerDetectionActivityLogFilter, $first: Int, $order: CustomerDetectionActivityLogOrder, $by: DetectionRuleLogicBy!, $id: ID!) {\n    customerDetection (id: $id) {\n        activityLogEntries (after: $after, filter: $filter, first: $first, order: $order) {\n            totalCount\n        }\n        customer {\n            id\n        }\n        displaySlug\n        draftVersion {\n            id\n        }\n        globalDetection {\n            connector {\n                documentationUrl\n                id\n                name\n                type\n            }\n            detectionRule {\n                description\n                id\n                logSourceTypes\n                logic (by: $by) {\n                    logic\n                    severity\n                    version\n                }\n                mitreTacticNames\n                mitreTacticTechniques {\n                    id\n                    name\n                }\n                name\n                severity\n                slug\n                state\n                updatedAt\n            }\n            detectionSource\n            displaySlug\n            id\n            logic\n            macros\n            sourceType\n            suppressionExpression\n            timeRange\n            versionNumber\n        }\n        id\n        versionNumber\n    }\n}",
    "customerDetectionActivityLogEntries": "query customerDetectionActivityLogEntries ($after: String, $filter: CustomerDetectionActivityLogFilter, $first: Int, $order: CustomerDetectionActivityLogOrder) {\n    customerDetectionActivityLogEntries (after: $after, filter: $filter, first: $first, order: $order) {\n        edges {\n            cursor\n            node {\n                activityLogType\n                createdAt\n                id\n                text\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
    "customerDetectionActivityLogEntry": "query customerDetectionActivityLogEntry ($after: String, $filter: CustomerDetectionActivityLogEntryCommentFilter, $first: Int, $order: CustomerDetectionActivityLogEntryCommentOrder, $id: ID!) {\n    customerDetectionActivityLogEntry (id: $id) {\n        activityLogType\n        comments (after: $after, filter: $filter, first: $first, order: $order) {\n            totalCount\n        }\n        createdAt\n        createdBy {\n            id\n        }\n        customer {\n            id\n        }\n        customerDetection {\n            id\n        }\n        draftCustomerDetection {\n            id\n        }\n        id\n        text\n    }\n}",
    "customerDetections": "query customerDetections ($after: String, $filter: CustomerDetectionFilter, $first: Int, $order: CustomerDetectionOrder) {\n    customerDetections (after: $after, filter: $filter, first: $first, order: $order) {\n        edges {\n            cursor\n            node {\n                createdAt\n                deployedLogic\n                detectionSource\n                displaySlug\n                enabled\n                id\n                sourceType\n                versionNumber\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
    "detectionRules": "query detectionRules ($after: String, $detectionRuleOrder: DetectionRuleOrder, $filter: DetectionRuleFilter, $first: Int) {\n    detectionRules (after: $after, detectionRuleOrder: $detectionRuleOrder, filter: $filter, first: $first) {\n        edges {\n            cursor\n            node {\n                description\n                id\n                logSourceTypes\n                mitreTacticNames\n                name\n                severity\n                slug\n                state\n                updatedAt\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
    "draftCustomerDetection": "query draftCustomerDetection ($after: String, $filter: CustomerDetectionActivityLogFilter, $first: Int, $order: CustomerDetectionActivityLogOrder, $by: DraftCustomerDetectionBy!) {\n    draftCustomerDetection (by: $by) {\n        activityLogEntries (after: $after, filter: $filter, first: $first, order: $order) {\n            totalCount\n        }\n        customer {\n            id\n        }\n        displaySlug\n        globalDetection {\n            connector {\n                documentationUrl\n                id\n                name\n                type\n            }\n            detectionRule {\n                description\n                id\n                logSourceTypes\n                mitreTacticNames\n                name\n                severity\n                slug\n                state\n                updatedAt\n            }\n            detectionSource\n            displaySlug\n            id\n            logic\n            macros\n            sourceType\n            suppressionExpression\n            timeRange\n            versionNumber\n        }\n        id\n        publishedVersion {\n            id\n        }\n    }\n}",
    "createActivityLogEntryComment": "mutation createActivityLogEntryComment ($comment: CreateActivityLogEntryCommentInput!) {\n    createActivityLogEntryComment (comment: $comment) {\n        comment {\n            activityLogEntry {\n                activityLogType\n                createdAt\n                id\n                text\n            }\n            createdAt\n            createdBy {\n                email\n                fullName\n                id\n                serviceNowId\n            }\n            customer {\n                active\n                headerSlug\n                id\n                name\n                residency\n                slug\n            }\n            id\n            text\n            type\n        }\n        success\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    @mcp.tool(name="customer_detection", description="Detections \u00b7 query customerDetection. Variables: after, filter, first, order, by, id. Example variables: {\"after\":\"T18w\",\"filter\":{\"activityLogType\":\"BULK_NEW_RULES_DEPLOYED\",\"activityLogTypes\":[\"BULK_NEW_RULES_DEPLOYED\"],\"bulkJobId\":\"<ID HERE>\",\"customerDetectionId\":\"<ID HERE>\",\"draftCustomerDetectionId\":\"<ID HERE>\",\"isBulk\":true,\"parentCustomerId\":\"\"},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy...")
    async def customer_detection(
        by: Annotated[Any, Field(description="GraphQL: DetectionRuleLogicBy!")],
        id: Annotated[str, Field(description="GraphQL: ID!")],
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerDetectionActivityLogFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerDetectionActivityLogOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["customerDetection"], {"by": by, "id": id, "after": after, "filter": filter, "first": first, "order": order}, customer_slug=customer_slug)

    @mcp.tool(name="customer_detection_activity_log_entries", description="Detections \u00b7 query customerDetectionActivityLogEntries. Variables: after, filter, first, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"activityLogType\":\"BULK_NEW_RULES_DEPLOYED\",\"activityLogTypes\":[\"BULK_NEW_RULES_DEPLOYED\"],\"bulkJobId\":\"<ID HERE>\",\"customerDetectionId\":\"<ID HERE>\",\"draftCustomerDetectionId\":\"<ID HERE>\",\"isBulk\":true,\"parentCustomerId\":\"\"},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy...")
    async def customer_detection_activity_log_entries(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerDetectionActivityLogFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerDetectionActivityLogOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["customerDetectionActivityLogEntries"], {"after": after, "filter": filter, "first": first, "order": order}, customer_slug=customer_slug)

    @mcp.tool(name="customer_detection_activity_log_entry", description="Detections \u00b7 query customerDetectionActivityLogEntry. Variables: after, filter, first, order, id. Example variables: {\"after\":\"T18w\",\"filter\":{\"types\":[\"PUBLIC\"],\"user\":\"<ID HERE>\"},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"CREATED_AT\"},\"id\":\"<ID HERE>\"}")
    async def customer_detection_activity_log_entry(
        id: Annotated[str, Field(description="GraphQL: ID!")],
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerDetectionActivityLogEntryCommentFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerDetectionActivityLogEntryCommentOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["customerDetectionActivityLogEntry"], {"id": id, "after": after, "filter": filter, "first": first, "order": order}, customer_slug=customer_slug)

    @mcp.tool(name="customer_detections", description="Detections \u00b7 query customerDetections. Variables: after, filter, first, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"createdAt\":{\"earliest\":\"2026-05-01T00:00:00.000Z\",\"latest\":\"2026-05-01T00:00:00.000Z\"},\"detectionRuleIds\":[\"<ID HERE>\"],\"displaySlugs\":[0],\"enabled\":true,\"ineligible\":true,\"integrationIds\":[\"<ID HERE>\"],\"sourceTypes\":[\"\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\"...")
    async def customer_detections(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerDetectionFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerDetectionOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["customerDetections"], {"after": after, "filter": filter, "first": first, "order": order}, customer_slug=customer_slug)

    @mcp.tool(name="detection_rules", description="Detections \u00b7 query detectionRules. Variables: after, detectionRuleOrder, filter, first. Example variables: {\"after\":\"T18w\",\"detectionRuleOrder\":{\"direction\":\"ASC\",\"orderBy\":\"ID\"},\"filter\":{\"authors\":{\"connectorId\":\"<ID HERE>\",\"reliaQuest\":true},\"deployedLocations\":{\"connectorId\":\"<ID HERE>\",\"digitalRiskProtection\":true,\"greymatter\":true},\"endDate\":\"2026-05-01T00:00:00.000Z\",\"ids\":[\"<ID HERE>\"],\"killch...")
    async def detection_rules(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        detectionRuleOrder: Annotated[Any | None, Field(default=None, description="GraphQL: DetectionRuleOrder")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: DetectionRuleFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["detectionRules"], {"after": after, "detectionRuleOrder": detectionRuleOrder, "filter": filter, "first": first}, customer_slug=customer_slug)

    @mcp.tool(name="draft_customer_detection", description="Detections \u00b7 query draftCustomerDetection. Variables: after, filter, first, order, by. Example variables: {\"after\":\"T18w\",\"filter\":{\"activityLogType\":\"BULK_NEW_RULES_DEPLOYED\",\"activityLogTypes\":[\"BULK_NEW_RULES_DEPLOYED\"],\"bulkJobId\":\"<ID HERE>\",\"customerDetectionId\":\"<ID HERE>\",\"draftCustomerDetectionId\":\"<ID HERE>\",\"isBulk\":true,\"parentCustomerId\":\"\"},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy...")
    async def draft_customer_detection(
        by: Annotated[Any, Field(description="GraphQL: DraftCustomerDetectionBy!")],
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerDetectionActivityLogFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerDetectionActivityLogOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["draftCustomerDetection"], {"by": by, "after": after, "filter": filter, "first": first, "order": order}, customer_slug=customer_slug)

    if not read_only:
        @mcp.tool(name="create_activity_log_entry_comment", description="Detections \u00b7 mutation createActivityLogEntryComment. Variables: comment. Example variables: {\"comment\":{\"activityLogEntryId\":\"<ID HERE>\",\"text\":\"\"}}")
        async def create_activity_log_entry_comment(
            comment: Annotated[Any, Field(description="GraphQL: CreateActivityLogEntryCommentInput!")],
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["createActivityLogEntryComment"], {"comment": comment}, customer_slug=customer_slug)

