"""GreyMatter MCP tools for domain: DRP Access Control.

GENERATED by scripts/generate_from_collection.py — do not edit by hand.
Regenerate via: python scripts/generate_from_collection.py
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

_DOC: dict[str, str] = {
    "accessControlPolicies": "query accessControlPolicies ($after: String, $customerId: ID, $first: Int, $policyFilter: AccessControlPolicyFilter, $policyOrder: AccessControlPolicyOrder) {\n    accessControlPolicies (after: $after, customerId: $customerId, first: $first, policyFilter: $policyFilter, policyOrder: $policyOrder) {\n        edges {\n            cursor\n            node {\n                description\n                displayName\n                id\n                name\n                resource\n                resourceType\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
    "accessControlPolicy": "query accessControlPolicy ($after: String, $first: Int, $notFilter: AccessControlPolicyFieldFilter, $order: AccessGroupOrder, $after1: String, $first1: Int, $after2: String, $first2: Int, $after3: String, $first3: Int, $notFilter1: AccessControlPolicyFieldFilter, $id: ID!) {\n    accessControlPolicy (id: $id) {\n        accessGroups (after: $after, first: $first, notFilter: $notFilter, order: $order) {\n            edges {\n                cursor\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n        customer {\n            accessControlPolicies (after: $after1, first: $first1) {\n                totalCount\n            }\n            active\n            headerSlug\n            id\n            name\n            residency\n            slug\n            users (after: $after2, first: $first2) {\n                totalCount\n            }\n        }\n        description\n        displayName\n        id\n        name\n        resource\n        resourceType\n        users (after: $after3, first: $first3, notFilter: $notFilter1) {\n            edges {\n                cursor\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n    }\n}",
    "accessControlResources": "query accessControlResources {\n    accessControlResources\n}",
    "createAccessControlPolicy": "mutation createAccessControlPolicy ($after: String, $first: Int, $notFilter: AccessControlPolicyFieldFilter, $order: AccessGroupOrder, $after1: String, $first1: Int, $notFilter1: AccessControlPolicyFieldFilter, $input: CreateAccessControlPolicyInput!) {\n    createAccessControlPolicy (input: $input) {\n        policy {\n            accessGroups (after: $after, first: $first, notFilter: $notFilter, order: $order) {\n                totalCount\n            }\n            customer {\n                active\n                headerSlug\n                id\n                name\n                residency\n                slug\n            }\n            description\n            displayName\n            id\n            name\n            resource\n            resourceType\n            users (after: $after1, first: $first1, notFilter: $notFilter1) {\n                totalCount\n            }\n        }\n        success\n    }\n}",
    "deleteAccessControlPolicy": "mutation deleteAccessControlPolicy ($after: String, $first: Int, $notFilter: AccessControlPolicyFieldFilter, $order: AccessGroupOrder, $after1: String, $first1: Int, $notFilter1: AccessControlPolicyFieldFilter, $id: ID!) {\n    deleteAccessControlPolicy (id: $id) {\n        policy {\n            accessGroups (after: $after, first: $first, notFilter: $notFilter, order: $order) {\n                totalCount\n            }\n            customer {\n                active\n                headerSlug\n                id\n                name\n                residency\n                slug\n            }\n            description\n            displayName\n            id\n            name\n            resource\n            resourceType\n            users (after: $after1, first: $first1, notFilter: $notFilter1) {\n                totalCount\n            }\n        }\n        success\n    }\n}",
    "updateAccessControlPolicies": "mutation updateAccessControlPolicies ($after: String, $first: Int, $notFilter: AccessControlPolicyFieldFilter, $order: AccessGroupOrder, $after1: String, $first1: Int, $notFilter1: AccessControlPolicyFieldFilter, $input: UpdateAccessControlPoliciesInput!) {\n    updateAccessControlPolicies (input: $input) {\n        policies {\n            accessGroups (after: $after, first: $first, notFilter: $notFilter, order: $order) {\n                totalCount\n            }\n            customer {\n                active\n                headerSlug\n                id\n                name\n                residency\n                slug\n            }\n            description\n            displayName\n            id\n            name\n            resource\n            resourceType\n            users (after: $after1, first: $first1, notFilter: $notFilter1) {\n                totalCount\n            }\n        }\n        success\n    }\n}",
    "updateAccessControlPolicy": "mutation updateAccessControlPolicy ($after: String, $first: Int, $notFilter: AccessControlPolicyFieldFilter, $order: AccessGroupOrder, $after1: String, $first1: Int, $notFilter1: AccessControlPolicyFieldFilter, $input: UpdateAccessControlPolicyInput!) {\n    updateAccessControlPolicy (input: $input) {\n        policy {\n            accessGroups (after: $after, first: $first, notFilter: $notFilter, order: $order) {\n                totalCount\n            }\n            customer {\n                active\n                headerSlug\n                id\n                name\n                residency\n                slug\n            }\n            description\n            displayName\n            id\n            name\n            resource\n            resourceType\n            users (after: $after1, first: $first1, notFilter: $notFilter1) {\n                totalCount\n            }\n        }\n        success\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    @mcp.tool(name="access_control_policies", description="DRP Access Control \u00b7 query accessControlPolicies. Variables: after, customerId, first, policyFilter, policyOrder. Example variables: {\"after\":\"T18w\",\"customerId\":\"<ID HERE>\",\"first\":10,\"policyFilter\":{\"name\":\"\",\"resources\":[\"\"]},\"policyOrder\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"}}")
    async def access_control_policies(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        customerId: Annotated[str | None, Field(default=None, description="GraphQL: ID")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        policyFilter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessControlPolicyFilter")] = None,
        policyOrder: Annotated[Any | None, Field(default=None, description="GraphQL: AccessControlPolicyOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["accessControlPolicies"], {"after": after, "customerId": customerId, "first": first, "policyFilter": policyFilter, "policyOrder": policyOrder}, customer_slug=customer_slug)

    @mcp.tool(name="access_control_policy", description="DRP Access Control \u00b7 query accessControlPolicy. Variables: after, first, notFilter, order, after1, first1, after2, first2, after3, first3, notFilter1, id. Example variables: {\"after\":\"T18w\",\"first\":10,\"notFilter\":{\"ids\":[\"<ID HERE>\"]},\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"first1\":10,\"after2\":\"T18w\",\"first2\":10,\"after3\":\"T18w\",\"first3\":10,\"notFilter1\":{\"ids\":[\"<ID HERE>\"]},\"id\":\"<ID HERE>\"}")
    async def access_control_policy(
        id: Annotated[str, Field(description="GraphQL: ID!")],
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        notFilter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessControlPolicyFieldFilter")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
        after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        after3: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        first3: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        notFilter1: Annotated[Any | None, Field(default=None, description="GraphQL: AccessControlPolicyFieldFilter")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["accessControlPolicy"], {"id": id, "after": after, "first": first, "notFilter": notFilter, "order": order, "after1": after1, "first1": first1, "after2": after2, "first2": first2, "after3": after3, "first3": first3, "notFilter1": notFilter1}, customer_slug=customer_slug)

    @mcp.tool(name="access_control_resources", description="DRP Access Control \u00b7 query accessControlResources. Example variables: {}")
    async def access_control_resources(
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["accessControlResources"], {}, customer_slug=customer_slug)

    if not read_only:
        @mcp.tool(name="create_access_control_policy", description="DRP Access Control \u00b7 mutation createAccessControlPolicy. Variables: after, first, notFilter, order, after1, first1, notFilter1, input. Example variables: {\"after\":\"T18w\",\"first\":10,\"notFilter\":{\"ids\":[\"<ID HERE>\"]},\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"first1\":10,\"notFilter1\":{\"ids\":[\"<ID HERE>\"]},\"input\":{\"accessGroups\":[\"<ID HERE>\"],\"customerId\":\"<ID HERE>\",\"description\":\"\",\"name\":\"\",\"resource\":\"\",\"users\":[\"<ID HERE>\"]}}")
        async def create_access_control_policy(
            input: Annotated[Any, Field(description="GraphQL: CreateAccessControlPolicyInput!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            notFilter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessControlPolicyFieldFilter")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            notFilter1: Annotated[Any | None, Field(default=None, description="GraphQL: AccessControlPolicyFieldFilter")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["createAccessControlPolicy"], {"input": input, "after": after, "first": first, "notFilter": notFilter, "order": order, "after1": after1, "first1": first1, "notFilter1": notFilter1}, customer_slug=customer_slug)

        @mcp.tool(name="delete_access_control_policy", description="DRP Access Control \u00b7 mutation deleteAccessControlPolicy. Variables: after, first, notFilter, order, after1, first1, notFilter1, id. Example variables: {\"after\":\"T18w\",\"first\":10,\"notFilter\":{\"ids\":[\"<ID HERE>\"]},\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"first1\":10,\"notFilter1\":{\"ids\":[\"<ID HERE>\"]},\"id\":\"<ID HERE>\"}")
        async def delete_access_control_policy(
            id: Annotated[str, Field(description="GraphQL: ID!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            notFilter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessControlPolicyFieldFilter")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            notFilter1: Annotated[Any | None, Field(default=None, description="GraphQL: AccessControlPolicyFieldFilter")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["deleteAccessControlPolicy"], {"id": id, "after": after, "first": first, "notFilter": notFilter, "order": order, "after1": after1, "first1": first1, "notFilter1": notFilter1}, customer_slug=customer_slug)

        @mcp.tool(name="update_access_control_policies", description="DRP Access Control \u00b7 mutation updateAccessControlPolicies. Variables: after, first, notFilter, order, after1, first1, notFilter1, input. Example variables: {\"after\":\"T18w\",\"first\":10,\"notFilter\":{\"ids\":[\"<ID HERE>\"]},\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"first1\":10,\"notFilter1\":{\"ids\":[\"<ID HERE>\"]},\"input\":{\"accessControlPolicyIds\":[\"<ID HERE>\"],\"accessGroups\":{\"add\":[\"<ID HERE>\"],\"addAll\":true,\"remove\":[\"<ID HERE>\"],\"remove...")
        async def update_access_control_policies(
            input: Annotated[Any, Field(description="GraphQL: UpdateAccessControlPoliciesInput!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            notFilter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessControlPolicyFieldFilter")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            notFilter1: Annotated[Any | None, Field(default=None, description="GraphQL: AccessControlPolicyFieldFilter")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["updateAccessControlPolicies"], {"input": input, "after": after, "first": first, "notFilter": notFilter, "order": order, "after1": after1, "first1": first1, "notFilter1": notFilter1}, customer_slug=customer_slug)

        @mcp.tool(name="update_access_control_policy", description="DRP Access Control \u00b7 mutation updateAccessControlPolicy. Variables: after, first, notFilter, order, after1, first1, notFilter1, input. Example variables: {\"after\":\"T18w\",\"first\":10,\"notFilter\":{\"ids\":[\"<ID HERE>\"]},\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"first1\":10,\"notFilter1\":{\"ids\":[\"<ID HERE>\"]},\"input\":{\"accessGroups\":{\"add\":[\"<ID HERE>\"],\"addAll\":true,\"remove\":[\"<ID HERE>\"],\"removeAll\":true,\"replace\":[\"<ID HERE>\"]},\"des...")
        async def update_access_control_policy(
            input: Annotated[Any, Field(description="GraphQL: UpdateAccessControlPolicyInput!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            notFilter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessControlPolicyFieldFilter")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            notFilter1: Annotated[Any | None, Field(default=None, description="GraphQL: AccessControlPolicyFieldFilter")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["updateAccessControlPolicy"], {"input": input, "after": after, "first": first, "notFilter": notFilter, "order": order, "after1": after1, "first1": first1, "notFilter1": notFilter1}, customer_slug=customer_slug)

