"""GreyMatter MCP tools for domain: Emergency Contacts.

GENERATED by scripts/generate_from_collection.py — DO NOT EDIT BY HAND.
Any manual change here will be overwritten the next time the generator runs; to change a
tool, edit the generator (or the source Postman collection) and regenerate via:
    python scripts/generate_from_collection.py

How this module works:
  - `register(mcp, *, read_only)` is the entry point: the server calls it to register every
    tool in this domain onto the shared FastMCP instance.
  - `_DOC` maps each GraphQL operation name to its (possibly trimmed/pruned) GraphQL document
    string. Each tool below looks up its document in `_DOC` at call time.
  - Each generated tool is a thin async wrapper: it accepts typed parameters (one per GraphQL
    variable, plus an optional `customer_slug` header override) and forwards them as GraphQL
    variables to `execute_operation`, which performs the actual HTTP request.
  - Query tools are always registered. Mutation tools are registered ONLY when `read_only`
    is False, so a read-only deployment never exposes state-changing operations.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

# operation name -> GraphQL document string (after exclusions/trims/pruning were applied).
_DOC: dict[str, str] = {
    "emergencyContact": "query emergencyContact ($after: String, $first: Int, $after1: String, $first1: Int, $after2: String, $filter: AccessGroupFilter, $first2: Int, $order: AccessGroupOrder, $after3: String, $filter1: PodFilter, $first3: Int, $order1: PodOrder, $after4: String, $filter2: RoleFilter, $first4: Int, $order2: RoleFilter, $id: ID!) {\n    emergencyContact (id: $id) {\n        callAttempts\n        callCategories\n        callOrder\n        callWindows {\n            daysOfWeek\n            endTime\n            startTime\n            timeZone\n        }\n        customer {\n            accessControlPolicies (after: $after, first: $first) {\n                totalCount\n            }\n            active\n            headerSlug\n            id\n            name\n            residency\n            slug\n            users (after: $after1, first: $first1) {\n                totalCount\n            }\n        }\n        fullName\n        id\n        onCall\n        phoneNumber\n        user {\n            accessGroups (after: $after2, filter: $filter, first: $first2, order: $order) {\n                totalCount\n            }\n            email\n            fullName\n            id\n            pods (after: $after3, filter: $filter1, first: $first3, order: $order1) {\n                totalCount\n            }\n            roles (after: $after4, filter: $filter2, first: $first4, order: $order2) {\n                totalCount\n            }\n            serviceNowId\n        }\n    }\n}",
    "emergencyContacts": "query emergencyContacts ($after: String, $filter: EmergencyContactFilter, $first: Int, $order: EmergencyContactOrder) {\n    emergencyContacts (after: $after, filter: $filter, first: $first, order: $order) {\n        edges {\n            cursor\n            node {\n                callAttempts\n                callCategories\n                callOrder\n                fullName\n                id\n                onCall\n                phoneNumber\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
    "createEmergencyContact": "mutation createEmergencyContact ($input: CreateEmergencyContactInput!) {\n    createEmergencyContact (input: $input) {\n        emergencyContact {\n            callAttempts\n            callCategories\n            callOrder\n            callWindows {\n                daysOfWeek\n                endTime\n                startTime\n                timeZone\n            }\n            customer {\n                active\n                headerSlug\n                id\n                name\n                residency\n                slug\n            }\n            fullName\n            id\n            onCall\n            phoneNumber\n            user {\n                email\n                fullName\n                id\n                serviceNowId\n            }\n        }\n        success\n    }\n}",
    "deleteEmergencyContact": "mutation deleteEmergencyContact ($id: ID!) {\n    deleteEmergencyContact (id: $id) {\n        success\n    }\n}",
    "updateCallOrder": "mutation updateCallOrder ($callOrder: Int!, $id: ID!) {\n    updateCallOrder (callOrder: $callOrder, id: $id) {\n        emergencyContacts {\n            callAttempts\n            callCategories\n            callOrder\n            callWindows {\n                daysOfWeek\n                endTime\n                startTime\n                timeZone\n            }\n            customer {\n                active\n                headerSlug\n                id\n                name\n                residency\n                slug\n            }\n            fullName\n            id\n            onCall\n            phoneNumber\n            user {\n                email\n                fullName\n                id\n                serviceNowId\n            }\n        }\n        success\n    }\n}",
    "updateEmergencyContact": "mutation updateEmergencyContact ($input: UpdateEmergencyContactInput!) {\n    updateEmergencyContact (input: $input) {\n        emergencyContact {\n            callAttempts\n            callCategories\n            callOrder\n            callWindows {\n                daysOfWeek\n                endTime\n                startTime\n                timeZone\n            }\n            customer {\n                active\n                headerSlug\n                id\n                name\n                residency\n                slug\n            }\n            fullName\n            id\n            onCall\n            phoneNumber\n            user {\n                email\n                fullName\n                id\n                serviceNowId\n            }\n        }\n        success\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    # --- Queries (always registered) ---
    # emergencyContact (query) — GraphQL operation, tool name "emergency_contact"
    @mcp.tool(name="emergency_contact", description="Emergency Contacts \u00b7 query emergencyContact. Variables: after, first, after1, first1, after2, filter, first2, order, after3, filter1, first3, order1, after4, filter2, first4, order2, id. Example variables: {\"after\":\"T18w\",\"first\":10,\"after1\":\"T18w\",\"first1\":10,\"after2\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first2\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after3\":\"T18w\",\"filter1\":{\"accessGro...")
    async def emergency_contact(
        id: Annotated[str, Field(description="GraphQL: ID!")],
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
        first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
        after3: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter1: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
        first3: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order1: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
        after4: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
        first4: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["emergencyContact"], {"id": id, "after": after, "first": first, "after1": after1, "first1": first1, "after2": after2, "filter": filter, "first2": first2, "order": order, "after3": after3, "filter1": filter1, "first3": first3, "order1": order1, "after4": after4, "filter2": filter2, "first4": first4, "order2": order2}, customer_slug=customer_slug)

    # emergencyContacts (query) — GraphQL operation, tool name "emergency_contacts"
    @mcp.tool(name="emergency_contacts", description="Emergency Contacts \u00b7 query emergencyContacts. Variables: after, filter, first, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"available\":true,\"callCategories\":[\"ENGINEERING\"],\"greyMatterUser\":true},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"CALL_CATEGORY\"}}")
    async def emergency_contacts(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: EmergencyContactFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: EmergencyContactOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["emergencyContacts"], {"after": after, "filter": filter, "first": first, "order": order}, customer_slug=customer_slug)

    if not read_only:
        # --- Mutations (registered only when read_only is False) ---
        # createEmergencyContact (mutation) — GraphQL operation, tool name "create_emergency_contact"
        @mcp.tool(name="create_emergency_contact", description="Emergency Contacts \u00b7 mutation createEmergencyContact. Variables: input. Example variables: {\"input\":{\"callAttempts\":0,\"callCategories\":[\"ENGINEERING\"],\"callOrder\":0,\"callWindows\":{\"daysOfWeek\":[\"FRIDAY\"],\"endTime\":\"\",\"startTime\":\"\",\"timeZone\":\"\"},\"fullName\":\"\",\"phoneNumber\":\"\",\"userId\":\"<ID HERE>\"}}")
        async def create_emergency_contact(
            input: Annotated[Any, Field(description="GraphQL: CreateEmergencyContactInput!")],
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["createEmergencyContact"], {"input": input}, customer_slug=customer_slug)

        # deleteEmergencyContact (mutation) — GraphQL operation, tool name "delete_emergency_contact"
        @mcp.tool(name="delete_emergency_contact", description="Emergency Contacts \u00b7 mutation deleteEmergencyContact. Variables: id. Example variables: {\"id\":\"<ID HERE>\"}")
        async def delete_emergency_contact(
            id: Annotated[str, Field(description="GraphQL: ID!")],
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["deleteEmergencyContact"], {"id": id}, customer_slug=customer_slug)

        # updateCallOrder (mutation) — GraphQL operation, tool name "update_call_order"
        @mcp.tool(name="update_call_order", description="Emergency Contacts \u00b7 mutation updateCallOrder. Variables: callOrder, id. Example variables: {\"callOrder\":0,\"id\":\"<ID HERE>\"}")
        async def update_call_order(
            callOrder: Annotated[int, Field(description="GraphQL: Int!")],
            id: Annotated[str, Field(description="GraphQL: ID!")],
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["updateCallOrder"], {"callOrder": callOrder, "id": id}, customer_slug=customer_slug)

        # updateEmergencyContact (mutation) — GraphQL operation, tool name "update_emergency_contact"
        @mcp.tool(name="update_emergency_contact", description="Emergency Contacts \u00b7 mutation updateEmergencyContact. Variables: input. Example variables: {\"input\":{\"callAttempts\":0,\"callCategories\":[\"ENGINEERING\"],\"callWindows\":{\"daysOfWeek\":[\"FRIDAY\"],\"endTime\":\"\",\"startTime\":\"\",\"timeZone\":\"\"},\"id\":\"<ID HERE>\",\"phoneNumber\":\"\"}}")
        async def update_emergency_contact(
            input: Annotated[Any, Field(description="GraphQL: UpdateEmergencyContactInput!")],
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["updateEmergencyContact"], {"input": input}, customer_slug=customer_slug)

