"""GreyMatter MCP tools for domain: Fields.

GENERATED by scripts/generate_from_collection.py — do not edit by hand.
Regenerate via: python scripts/generate_from_collection.py
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

_DOC: dict[str, str] = {
    "greymatterField": "query greymatterField ($by: GreyMatterFieldBy!) {\n    greymatterField (by: $by) {\n        description\n        displayName\n        id\n        name\n        serviceNowName\n        type\n    }\n}",
    "greymatterFields": "query greymatterFields ($after: String, $filter: GreyMatterFieldFilter, $first: Int, $order: GreyMatterFieldOrder) {\n    greymatterFields (after: $after, filter: $filter, first: $first, order: $order) {\n        edges {\n            cursor\n            node {\n                description\n                displayName\n                id\n                name\n                serviceNowName\n                type\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    @mcp.tool(name="greymatter_field", description="Fields \u00b7 query greymatterField. Variables: by. Example variables: {\"by\":{\"id\":\"<ID HERE>\",\"name\":\"\"}}")
    async def greymatter_field(
        by: Annotated[Any, Field(description="GraphQL: GreyMatterFieldBy!")],
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["greymatterField"], {"by": by}, customer_slug=customer_slug)

    @mcp.tool(name="greymatter_fields", description="Fields \u00b7 query greymatterFields. Variables: after, filter, first, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"ids\":[\"<ID HERE>\"],\"search\":\"\"},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"}}")
    async def greymatter_fields(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: GreyMatterFieldFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: GreyMatterFieldOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["greymatterFields"], {"after": after, "filter": filter, "first": first, "order": order}, customer_slug=customer_slug)

