"""GreyMatter MCP tools for domain: Identities.

GENERATED by scripts/generate_from_collection.py — do not edit by hand.
Regenerate via: python scripts/generate_from_collection.py
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

_DOC: dict[str, str] = {
    "identities": "query identities ($after: String, $filter: IdentityFilter, $first: Int, $order: IdentityOrder) {\n    identities (after: $after, filter: $filter, first: $first, order: $order) {\n        edges {\n            cursor\n            node {\n                createdAt\n                group\n                id\n                name\n                role\n                workLocation\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    @mcp.tool(name="identities", description="Identities \u00b7 query identities. Variables: after, filter, first, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"created\":{\"date\":\"2026-05-01T00:00:00.000Z\",\"operator\":\"AFTER\"},\"groups\":[\"\"],\"roles\":[\"\"],\"search\":\"\",\"workLocations\":[\"\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"GROUP\"}}")
    async def identities(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: IdentityFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: IdentityOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["identities"], {"after": after, "filter": filter, "first": first, "order": order}, customer_slug=customer_slug)

