"""GreyMatter MCP tools for domain: Indicators.

GENERATED by scripts/generate_from_collection.py — DO NOT EDIT BY HAND.
Any manual change here will be overwritten the next time the generator runs; to change a
tool, edit the generator (or the source Postman collection) and regenerate via:
    python scripts/generate_from_collection.py

How this module works:
  - `register(mcp, *, read_only)` is the entry point: the server calls it to register every
    tool in this domain onto the shared FastMCP instance.
  - `_DOC` maps each GraphQL operation name to its (possibly trimmed/pruned) GraphQL document
    string. Each tool below looks up its document in `_DOC` at call time.
  - Each generated tool is a thin async wrapper: it accepts typed parameters (one per GraphQL
    variable, plus an optional `customer_slug` header override) and forwards them as GraphQL
    variables to `execute_operation`, which performs the actual HTTP request.
  - Query tools are always registered. Mutation tools are registered ONLY when `read_only`
    is False, so a read-only deployment never exposes state-changing operations.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

# operation name -> GraphQL document string (after exclusions/trims/pruning were applied).
_DOC: dict[str, str] = {
    "indicator": "query indicator ($by: IOCBy!) {\n    indicator (by: $by) {\n        city\n        countScore\n        country\n        description\n        feedNames\n        firstSeenAt\n        id\n        lastSeenAt\n        name\n        region\n        reliabilityScore\n        severity\n        threatScore\n        type\n    }\n}",
    "indicators": "query indicators ($after: String, $filter: IndicatorFilter, $first: Int, $order: IndicatorOrder) {\n    indicators (after: $after, filter: $filter, first: $first, order: $order) {\n        edges {\n            cursor\n            node {\n                city\n                countScore\n                country\n                description\n                feedNames\n                firstSeenAt\n                id\n                lastSeenAt\n                name\n                region\n                reliabilityScore\n                severity\n                threatScore\n                type\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    # --- Queries (always registered) ---
    # indicator (query) — GraphQL operation, tool name "indicator"
    @mcp.tool(name="indicator", description="Indicators \u00b7 query indicator. Variables: by. Example variables: {\"by\":{\"id\":\"<ID HERE>\",\"input\":{\"name\":\"\",\"type\":\"CIDR\"}}}")
    async def indicator(
        by: Annotated[Any, Field(description="GraphQL: IOCBy!")],
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["indicator"], {"by": by}, customer_slug=customer_slug)

    # indicators (query) — GraphQL operation, tool name "indicators"
    @mcp.tool(name="indicators", description="Indicators \u00b7 query indicators. Variables: after, filter, first, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"feedNames\":[\"\"],\"lastSeenAt\":{\"earliest\":\"2026-05-01T00:00:00.000Z\",\"latest\":\"2026-05-01T00:00:00.000Z\"},\"names\":[\"\"],\"severity\":[\"CRITICAL\"],\"type\":[\"CIDR\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"LAST_SEEN\"}}")
    async def indicators(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: IndicatorFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: IndicatorOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["indicators"], {"after": after, "filter": filter, "first": first, "order": order}, customer_slug=customer_slug)

