"""GreyMatter MCP tools for domain: Indicators.

GENERATED by scripts/generate_from_collection.py — do not edit by hand.
Regenerate via: python scripts/generate_from_collection.py
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

_DOC: dict[str, str] = {
    "indicator": "query indicator ($by: IOCBy!) {\n    indicator (by: $by) {\n        city\n        countScore\n        country\n        description\n        feedNames\n        firstSeenAt\n        id\n        lastSeenAt\n        name\n        region\n        reliabilityScore\n        severity\n        threatScore\n        type\n    }\n}",
    "indicators": "query indicators ($after: String, $filter: IndicatorFilter, $first: Int, $order: IndicatorOrder) {\n    indicators (after: $after, filter: $filter, first: $first, order: $order) {\n        edges {\n            cursor\n            node {\n                city\n                countScore\n                country\n                description\n                feedNames\n                firstSeenAt\n                id\n                lastSeenAt\n                name\n                region\n                reliabilityScore\n                severity\n                threatScore\n                type\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    @mcp.tool(name="indicator", description="Indicators \u00b7 query indicator. Variables: by. Example variables: {\"by\":{\"id\":\"<ID HERE>\",\"input\":{\"name\":\"\",\"type\":\"CIDR\"}}}")
    async def indicator(
        by: Annotated[Any, Field(description="GraphQL: IOCBy!")],
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["indicator"], {"by": by}, customer_slug=customer_slug)

    @mcp.tool(name="indicators", description="Indicators \u00b7 query indicators. Variables: after, filter, first, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"feedNames\":[\"\"],\"lastSeenAt\":{\"earliest\":\"2026-05-01T00:00:00.000Z\",\"latest\":\"2026-05-01T00:00:00.000Z\"},\"names\":[\"\"],\"severity\":[\"CRITICAL\"],\"type\":[\"CIDR\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"LAST_SEEN\"}}")
    async def indicators(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: IndicatorFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: IndicatorOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["indicators"], {"after": after, "filter": filter, "first": first, "order": order}, customer_slug=customer_slug)

