"""GreyMatter MCP tools for domain: Query Management.

GENERATED by scripts/generate_from_collection.py — do not edit by hand.
Regenerate via: python scripts/generate_from_collection.py
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

_DOC: dict[str, str] = {
    "integration": "query integration ($after: String, $filter: IntegrationActivityLogFilter, $first: Int, $order: IntegrationActivityLogOrder, $after1: String, $first1: Int, $after2: String, $first2: Int, $id: ID!) {\n    integration (id: $id) {\n        activity (after: $after, filter: $filter, first: $first, order: $order) {\n            edges {\n                cursor\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n        connectionStatus\n        connector {\n            documentationUrl\n            id\n            name\n            type\n        }\n        enabled\n        id\n        lastConnectionTest\n        lastUsed\n        name\n        sharedBy {\n            accessControlPolicies (after: $after1, first: $first1) {\n                totalCount\n            }\n            active\n            headerSlug\n            id\n            name\n            residency\n            slug\n            users (after: $after2, first: $first2) {\n                totalCount\n            }\n        }\n    }\n}",
    "integrations": "query integrations ($after: String, $first: Int, $integrationFilter: IntegrationFilter, $integrationOrder: IntegrationOrder) {\n    integrations (after: $after, first: $first, integrationFilter: $integrationFilter, integrationOrder: $integrationOrder) {\n        edges {\n            cursor\n            node {\n                connectionStatus\n                enabled\n                id\n                lastConnectionTest\n                lastUsed\n                name\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
    "searchHistory": "query searchHistory ($after: String, $by: QueryBatchSearchBy!, $filter: QueryBatchFilter, $first: Int, $order: QueryBatchOrder) {\n    searchHistory (after: $after, by: $by, filter: $filter, first: $first, order: $order) {\n        edges {\n            cursor\n            node {\n                id\n                name\n                state\n                type\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    @mcp.tool(name="integration", description="Query Management \u00b7 query integration. Variables: after, filter, first, order, after1, first1, after2, first2, id. Example variables: {\"after\":\"T18w\",\"filter\":{\"created\":{\"earliest\":\"2026-05-01T00:00:00.000Z\",\"latest\":\"2026-05-01T00:00:00.000Z\"},\"types\":[\"CONFIGURATION_CHANGED\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"CREATED_AT\"},\"after1\":\"T18w\",\"first1\":10,\"after2\":\"T18w\",\"first2\":10,\"id\":\"<ID HERE>\"}")
    async def integration(
        id: Annotated[str, Field(description="GraphQL: ID!")],
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: IntegrationActivityLogFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: IntegrationActivityLogOrder")] = None,
        after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["integration"], {"id": id, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "first1": first1, "after2": after2, "first2": first2}, customer_slug=customer_slug)

    @mcp.tool(name="integrations", description="Query Management \u00b7 query integrations. Variables: after, first, integrationFilter, integrationOrder. Example variables: {\"after\":\"T18w\",\"first\":10,\"integrationFilter\":{\"connectionStatus\":\"CONNECTED\",\"connectorNames\":[\"\"],\"connectorTypes\":[\"ANTIVIRUS\"],\"enabled\":true,\"ids\":[\"<ID HERE>\"],\"search\":\"\"},\"integrationOrder\":{\"direction\":\"ASC\",\"orderBy\":\"CONNECTOR_NAME\"}}")
    async def integrations(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        integrationFilter: Annotated[Any | None, Field(default=None, description="GraphQL: IntegrationFilter")] = None,
        integrationOrder: Annotated[Any | None, Field(default=None, description="GraphQL: IntegrationOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["integrations"], {"after": after, "first": first, "integrationFilter": integrationFilter, "integrationOrder": integrationOrder}, customer_slug=customer_slug)

    @mcp.tool(name="search_history", description="Query Management \u00b7 query searchHistory. Variables: after, by, filter, first, order. Example variables: {\"after\":\"T18w\",\"by\":{\"incidentId\":\"<ID HERE>\"},\"filter\":{\"includeArchived\":true},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"CREATED_AT\"}}")
    async def search_history(
        by: Annotated[Any, Field(description="GraphQL: QueryBatchSearchBy!")],
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: QueryBatchFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: QueryBatchOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["searchHistory"], {"by": by, "after": after, "filter": filter, "first": first, "order": order}, customer_slug=customer_slug)

