"""GreyMatter MCP tools for domain: User Activity.

GENERATED by scripts/generate_from_collection.py — do not edit by hand.
Regenerate via: python scripts/generate_from_collection.py
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

_DOC: dict[str, str] = {
    "audits": "query audits ($after: String, $filter: AuditActionFilter, $first: Int, $order: AuditActionOrder) {\n    audits (after: $after, filter: $filter, first: $first, order: $order) {\n        edges {\n            cursor\n            node {\n                actionType\n                createdAt\n                id\n                objectId\n                objectName\n                objectType\n            }\n        }\n        pageInfo {\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            startCursor\n        }\n        totalCount\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    @mcp.tool(name="audits", description="User Activity \u00b7 query audits. Variables: after, filter, first, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"objectId\":\"\"},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"ACTION_TYPE\"}}")
    async def audits(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: AuditActionFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: AuditActionOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["audits"], {"after": after, "filter": filter, "first": first, "order": order}, customer_slug=customer_slug)

