"""GreyMatter MCP tools for domain: User.

GENERATED by scripts/generate_from_collection.py — DO NOT EDIT BY HAND.
Any manual change here will be overwritten the next time the generator runs; to change a
tool, edit the generator (or the source Postman collection) and regenerate via:
    python scripts/generate_from_collection.py

How this module works:
  - `register(mcp, *, read_only)` is the entry point: the server calls it to register every
    tool in this domain onto the shared FastMCP instance.
  - `_DOC` maps each GraphQL operation name to its (possibly trimmed/pruned) GraphQL document
    string. Each tool below looks up its document in `_DOC` at call time.
  - Each generated tool is a thin async wrapper: it accepts typed parameters (one per GraphQL
    variable, plus an optional `customer_slug` header override) and forwards them as GraphQL
    variables to `execute_operation`, which performs the actual HTTP request.
  - Query tools are always registered. Mutation tools are registered ONLY when `read_only`
    is False, so a read-only deployment never exposes state-changing operations.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

# operation name -> GraphQL document string (after exclusions/trims/pruning were applied).
_DOC: dict[str, str] = {
    "me": "query me ($after: String, $filter: CustomerFilter, $first: Int, $order: CustomerOrder) {\n    me {\n        customers (after: $after, filter: $filter, first: $first, order: $order) {\n            totalCount\n        }\n        email\n        fullName\n        id\n        serviceNowId\n    }\n}",
    "user": "query user ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: PodFilter, $first1: Int, $order1: PodOrder, $after2: String, $filter2: RoleFilter, $first2: Int, $order2: RoleOrder, $id: ID!) {\n    user (id: $id) {\n        accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n            edges {\n                cursor\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n        email\n        fullName\n        id\n        pods (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n            edges {\n                cursor\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n        roles (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n            edges {\n                cursor\n            }\n            pageInfo {\n                endCursor\n                hasNextPage\n                hasPreviousPage\n                startCursor\n            }\n            totalCount\n        }\n        serviceNowId\n    }\n}",
    "createUser": "mutation createUser ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: PodFilter, $first1: Int, $order1: PodOrder, $after2: String, $filter2: RoleFilter, $first2: Int, $order2: RoleOrder, $input: CreateUserInput!) {\n    createUser (input: $input) {\n        success\n        user {\n            accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            email\n            fullName\n            id\n            pods (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n                totalCount\n            }\n            roles (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n                totalCount\n            }\n            serviceNowId\n        }\n    }\n}",
    "deleteUser": "mutation deleteUser ($user: ID!) {\n    deleteUser (user: $user) {\n        success\n    }\n}",
    "disableUser": "mutation disableUser ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: PodFilter, $first1: Int, $order1: PodOrder, $after2: String, $filter2: RoleFilter, $first2: Int, $order2: RoleOrder, $user: ID!) {\n    disableUser (user: $user) {\n        success\n        user {\n            accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            email\n            fullName\n            id\n            pods (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n                totalCount\n            }\n            roles (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n                totalCount\n            }\n            serviceNowId\n        }\n    }\n}",
    "enableUser": "mutation enableUser ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: PodFilter, $first1: Int, $order1: PodOrder, $after2: String, $filter2: RoleFilter, $first2: Int, $order2: RoleOrder, $user: ID!) {\n    enableUser (user: $user) {\n        success\n        user {\n            accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            email\n            fullName\n            id\n            pods (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n                totalCount\n            }\n            roles (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n                totalCount\n            }\n            serviceNowId\n        }\n    }\n}",
    "generatePasswordLink": "mutation generatePasswordLink ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: PodFilter, $first1: Int, $order1: PodOrder, $after2: String, $filter2: RoleFilter, $first2: Int, $order2: RoleOrder, $user: ID!) {\n    generatePasswordLink (user: $user) {\n        link\n        success\n        user {\n            accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            email\n            fullName\n            id\n            pods (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n                totalCount\n            }\n            roles (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n                totalCount\n            }\n            serviceNowId\n        }\n    }\n}",
    "resendInvite": "mutation resendInvite ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: PodFilter, $first1: Int, $order1: PodOrder, $after2: String, $filter2: RoleFilter, $first2: Int, $order2: RoleOrder, $user: ID!) {\n    resendInvite (user: $user) {\n        success\n        user {\n            accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            email\n            fullName\n            id\n            pods (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n                totalCount\n            }\n            roles (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n                totalCount\n            }\n            serviceNowId\n        }\n    }\n}",
    "resetMfa": "mutation resetMfa ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: PodFilter, $first1: Int, $order1: PodOrder, $after2: String, $filter2: RoleFilter, $first2: Int, $order2: RoleOrder, $user: ID!) {\n    resetMfa (user: $user) {\n        success\n        user {\n            accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            email\n            fullName\n            id\n            pods (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n                totalCount\n            }\n            roles (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n                totalCount\n            }\n            serviceNowId\n        }\n    }\n}",
    "sendForgotPassword": "mutation sendForgotPassword ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: PodFilter, $first1: Int, $order1: PodOrder, $after2: String, $filter2: RoleFilter, $first2: Int, $order2: RoleOrder, $user: ID!) {\n    sendForgotPassword (user: $user) {\n        success\n        user {\n            accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            email\n            fullName\n            id\n            pods (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n                totalCount\n            }\n            roles (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n                totalCount\n            }\n            serviceNowId\n        }\n    }\n}",
    "updateUser": "mutation updateUser ($after: String, $filter: AccessGroupFilter, $first: Int, $order: AccessGroupOrder, $after1: String, $filter1: PodFilter, $first1: Int, $order1: PodOrder, $after2: String, $filter2: RoleFilter, $first2: Int, $order2: RoleOrder, $input: UpdateUserInput!) {\n    updateUser (input: $input) {\n        success\n        user {\n            accessGroups (after: $after, filter: $filter, first: $first, order: $order) {\n                totalCount\n            }\n            email\n            fullName\n            id\n            pods (after: $after1, filter: $filter1, first: $first1, order: $order1) {\n                totalCount\n            }\n            roles (after: $after2, filter: $filter2, first: $first2, order: $order2) {\n                totalCount\n            }\n            serviceNowId\n        }\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    # --- Queries (always registered) ---
    # me (query) — GraphQL operation, tool name "me"
    @mcp.tool(name="me", description="User \u00b7 query me. Variables: after, filter, first, order. Example variables: {\"after\":\"T18w\",\"filter\":{\"accessGroups\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"}}")
    async def me(
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: CustomerOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["me"], {"after": after, "filter": filter, "first": first, "order": order}, customer_slug=customer_slug)

    # user (query) — GraphQL operation, tool name "user"
    @mcp.tool(name="user", description="User \u00b7 query user. Variables: after, filter, first, order, after1, filter1, first1, order1, after2, filter2, first2, order2, id. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID...")
    async def user(
        id: Annotated[str, Field(description="GraphQL: ID!")],
        after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
        first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
        after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter1: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
        first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order1: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
        after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
        filter2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
        first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
        order2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleOrder")] = None,
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["user"], {"id": id, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

    if not read_only:
        # --- Mutations (registered only when read_only is False) ---
        # createUser (mutation) — GraphQL operation, tool name "create_user"
        @mcp.tool(name="create_user", description="User \u00b7 mutation createUser. Variables: after, filter, first, order, after1, filter1, first1, order1, after2, filter2, first2, order2, input. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID...")
        async def create_user(
            input: Annotated[Any, Field(description="GraphQL: CreateUserInput!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter1: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order1: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
            after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
            first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleOrder")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["createUser"], {"input": input, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

        # deleteUser (mutation) — GraphQL operation, tool name "delete_user"
        @mcp.tool(name="delete_user", description="User \u00b7 mutation deleteUser. Variables: user. Example variables: {\"user\":\"<ID HERE>\"}")
        async def delete_user(
            user: Annotated[str, Field(description="GraphQL: ID!")],
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["deleteUser"], {"user": user}, customer_slug=customer_slug)

        # disableUser (mutation) — GraphQL operation, tool name "disable_user"
        @mcp.tool(name="disable_user", description="User \u00b7 mutation disableUser. Variables: after, filter, first, order, after1, filter1, first1, order1, after2, filter2, first2, order2, user. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID...")
        async def disable_user(
            user: Annotated[str, Field(description="GraphQL: ID!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter1: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order1: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
            after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
            first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleOrder")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["disableUser"], {"user": user, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

        # enableUser (mutation) — GraphQL operation, tool name "enable_user"
        @mcp.tool(name="enable_user", description="User \u00b7 mutation enableUser. Variables: after, filter, first, order, after1, filter1, first1, order1, after2, filter2, first2, order2, user. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID...")
        async def enable_user(
            user: Annotated[str, Field(description="GraphQL: ID!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter1: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order1: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
            after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
            first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleOrder")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["enableUser"], {"user": user, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

        # generatePasswordLink (mutation) — GraphQL operation, tool name "generate_password_link"
        @mcp.tool(name="generate_password_link", description="User \u00b7 mutation generatePasswordLink. Variables: after, filter, first, order, after1, filter1, first1, order1, after2, filter2, first2, order2, user. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID...")
        async def generate_password_link(
            user: Annotated[str, Field(description="GraphQL: ID!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter1: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order1: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
            after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
            first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleOrder")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["generatePasswordLink"], {"user": user, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

        # resendInvite (mutation) — GraphQL operation, tool name "resend_invite"
        @mcp.tool(name="resend_invite", description="User \u00b7 mutation resendInvite. Variables: after, filter, first, order, after1, filter1, first1, order1, after2, filter2, first2, order2, user. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID...")
        async def resend_invite(
            user: Annotated[str, Field(description="GraphQL: ID!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter1: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order1: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
            after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
            first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleOrder")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["resendInvite"], {"user": user, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

        # resetMfa (mutation) — GraphQL operation, tool name "reset_mfa"
        @mcp.tool(name="reset_mfa", description="User \u00b7 mutation resetMfa. Variables: after, filter, first, order, after1, filter1, first1, order1, after2, filter2, first2, order2, user. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID...")
        async def reset_mfa(
            user: Annotated[str, Field(description="GraphQL: ID!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter1: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order1: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
            after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
            first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleOrder")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["resetMfa"], {"user": user, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

        # sendForgotPassword (mutation) — GraphQL operation, tool name "send_forgot_password"
        @mcp.tool(name="send_forgot_password", description="User \u00b7 mutation sendForgotPassword. Variables: after, filter, first, order, after1, filter1, first1, order1, after2, filter2, first2, order2, user. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID...")
        async def send_forgot_password(
            user: Annotated[str, Field(description="GraphQL: ID!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter1: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order1: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
            after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
            first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleOrder")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["sendForgotPassword"], {"user": user, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

        # updateUser (mutation) — GraphQL operation, tool name "update_user"
        @mcp.tool(name="update_user", description="User \u00b7 mutation updateUser. Variables: after, filter, first, order, after1, filter1, first1, order1, after2, filter2, first2, order2, input. Example variables: {\"after\":\"T18w\",\"filter\":{\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID HERE>\"],\"name\":\"\",\"pods\":[\"<ID HERE>\"],\"roles\":[\"<ID HERE>\"],\"users\":[\"<ID HERE>\"]},\"first\":10,\"order\":{\"direction\":\"ASC\",\"orderBy\":\"NAME\"},\"after1\":\"T18w\",\"filter1\":{\"accessGroups\":[\"<ID HERE>\"],\"customers\":[\"<ID HERE>\"],\"ids\":[\"<ID...")
        async def update_user(
            input: Annotated[Any, Field(description="GraphQL: UpdateUserInput!")],
            after: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupFilter")] = None,
            first: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order: Annotated[Any | None, Field(default=None, description="GraphQL: AccessGroupOrder")] = None,
            after1: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter1: Annotated[Any | None, Field(default=None, description="GraphQL: PodFilter")] = None,
            first1: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order1: Annotated[Any | None, Field(default=None, description="GraphQL: PodOrder")] = None,
            after2: Annotated[str | None, Field(default=None, description="GraphQL: String")] = None,
            filter2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleFilter")] = None,
            first2: Annotated[int | None, Field(default=None, description="GraphQL: Int")] = None,
            order2: Annotated[Any | None, Field(default=None, description="GraphQL: RoleOrder")] = None,
            customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
        ) -> Any:
            return await execute_operation(_DOC["updateUser"], {"input": input, "after": after, "filter": filter, "first": first, "order": order, "after1": after1, "filter1": filter1, "first1": first1, "order1": order1, "after2": after2, "filter2": filter2, "first2": first2, "order2": order2}, customer_slug=customer_slug)

