"""GreyMatter MCP tools for domain: Utilities.

GENERATED by scripts/generate_from_collection.py — do not edit by hand.
Regenerate via: python scripts/generate_from_collection.py
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

_DOC: dict[str, str] = {
    "node": "query node ($id: ID!) {\n    node (id: $id) {\n        id\n    }\n}",
    "rateLimit": "query rateLimit {\n    rateLimit {\n        cost\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    @mcp.tool(name="node", description="Utilities \u00b7 query node. Variables: id. Example variables: {\"id\":\"<ID HERE>\"}")
    async def node(
        id: Annotated[str, Field(description="GraphQL: ID!")],
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["node"], {"id": id}, customer_slug=customer_slug)

    @mcp.tool(name="rate_limit", description="Utilities \u00b7 query rateLimit. Example variables: {}")
    async def rate_limit(
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["rateLimit"], {}, customer_slug=customer_slug)

