"""GreyMatter MCP tools for domain: Utilities.

GENERATED by scripts/generate_from_collection.py — DO NOT EDIT BY HAND.
Any manual change here will be overwritten the next time the generator runs; to change a
tool, edit the generator (or the source Postman collection) and regenerate via:
    python scripts/generate_from_collection.py

How this module works:
  - `register(mcp, *, read_only)` is the entry point: the server calls it to register every
    tool in this domain onto the shared FastMCP instance.
  - `_DOC` maps each GraphQL operation name to its (possibly trimmed/pruned) GraphQL document
    string. Each tool below looks up its document in `_DOC` at call time.
  - Each generated tool is a thin async wrapper: it accepts typed parameters (one per GraphQL
    variable, plus an optional `customer_slug` header override) and forwards them as GraphQL
    variables to `execute_operation`, which performs the actual HTTP request.
  - Query tools are always registered. Mutation tools are registered ONLY when `read_only`
    is False, so a read-only deployment never exposes state-changing operations.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_operation

# operation name -> GraphQL document string (after exclusions/trims/pruning were applied).
_DOC: dict[str, str] = {
    "node": "query node ($id: ID!) {\n    node (id: $id) {\n        id\n    }\n}",
    "rateLimit": "query rateLimit {\n    rateLimit {\n        cost\n    }\n}",
}


def register(mcp: FastMCP, *, read_only: bool) -> None:
    # --- Queries (always registered) ---
    # node (query) — GraphQL operation, tool name "node"
    @mcp.tool(name="node", description="Utilities \u00b7 query node. Variables: id. Example variables: {\"id\":\"<ID HERE>\"}")
    async def node(
        id: Annotated[str, Field(description="GraphQL: ID!")],
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["node"], {"id": id}, customer_slug=customer_slug)

    # rateLimit (query) — GraphQL operation, tool name "rate_limit"
    @mcp.tool(name="rate_limit", description="Return current GreyMatter API rate-limit usage (limit is 5000 points/hour per company account). Example variables: {}")
    async def rate_limit(
        customer_slug: Annotated[str | None, Field(default=None, description="Override the x-reliaquest-customer (OpCo) header.")] = None,
    ) -> Any:
        return await execute_operation(_DOC["rateLimit"], {}, customer_slug=customer_slug)

